docker stop tfserving1_1
docker stop tfserving1_2
docker rm tfserving1_1
docker rm tfserving1_2
docker stop tfserving2_1
docker stop tfserving2_2
docker rm tfserving2_1
docker rm tfserving2_2
docker stop tfserving3_1
docker stop tfserving3_2
docker rm tfserving3_1
docker rm tfserving3_2
docker stop tfserving4_1
docker stop tfserving4_2
docker rm tfserving4_1
docker rm tfserving4_2
